# Generated by Django 3.0.8 on 2020-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('LT', 'Lithuania'), ('UK', 'United Kingdom'), ('PL', 'Poland')], max_length=2)),
            ],
        ),
    ]
